name: dorilla_games
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # widget slider
  carousel_slider: ^4.2.1

  # icons
  cupertino_icons: ^1.0.2

  # email service
  emailjs: ^1.1.0

  # animation
  flare_flutter: ^3.0.2

  # state management
  flutter_bloc: ^8.1.3

  # svg
  flutter_svg:

  # url launch
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/animation/
    - assets/images/
    - assets/svg/
    - assets/jpg/

  fonts:
    - family: FelixTi
      fonts:
        - asset: assets/fonts/FELIXTI.TTF

    - family: Bodoni
      fonts:
        - asset: assets/fonts/Bodoni.ttf
